Vagrant.configure(2) do |config|
  config.vm.box = "yungsang/coreos"
  config.vm.synced_folder ".", "/home/core/v", id: "core", :nfs => true,  :mount_options   => ['nolock,vers=3,udp']

  config.vm.network "forwarded_port", guest: 1883, host: 1883

  config.vm.provider "parallels" do |prl|
    prl.memory = 512
    prl.cpus = 1
  end
  
  config.vm.provision "docker" do |d|
    d.build_image "v"
  end
end
