# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "AntonioMeireles/coreos-stable"

  config.vm.synced_folder ".", "/home/core/JetMQ", id: "core", :nfs => true,  :mount_options   => ['nolock,vers=3,udp']

  config.vm.network "forwarded_port", guest: 5601, host: 5601

end
